### ISSUE TITLE
Решение не соответствует поставленной задаче

### ISSUE THREAD

**Issue by dcby** [AndreiYakubovich/SoftClubTask#1]
Условием задачи было создание двух больших списков (по 500К уникальных записей каждый), которые бы пересекались примерно на 60%. В решении же используюся списки, содержащие 6 и 8 элементов. Так же необходимо было реализовать несколько алгоритмов сравнения списков и **указать почему** конктретный алгоритм является наибыстрейшим.

**Comment by AndreiYakubovich** [comment]
Реализовал генерацию коллекций и нахождение одинаковых элементов двумя методами. 
Не до конца понял где нужно указать какой из алгоритмов лучший, поэтому вывел результаты обоих в консоль и моё предположение почему LINQ запрос для коллекции работает быстрее.
